### ISSUE TITLE
请教中文搜索的实现方法

### ISSUE THREAD

**Issue by wormone** [wtx358/wtxlog#3]
flask-whoosh 不能直接支持中文分词，不知如何配置……

**Comment by wormone** [comment]
已解决，参照以下方法：
https://github.com/fxsjy/jieba/blob/master/test/test_whoosh.py
http://blog.csdn.net/wenxuansoft/article/details/8170714

**Comment by wtx358** [comment]
非常感谢 @wormone 的分享。
